FROM node:20.19-alpine3.20

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY src ./src
COPY index.html .
COPY vite.config.js .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
